#include "market_data/provider.hpp"

namespace market_data {
std::string_view to_string(ProviderId value) noexcept { switch(value){case ProviderId::synthetic:return "synthetic";case ProviderId::ctp:return "ctp";case ProviderId::ibkr:return "ibkr";case ProviderId::akshare:return "akshare";}return "unknown"; }
std::string_view to_string(ProviderState value) noexcept { switch(value){case ProviderState::stopped:return "STOPPED";case ProviderState::starting:return "STARTING";case ProviderState::connecting:return "CONNECTING";case ProviderState::authenticating:return "AUTHENTICATING";case ProviderState::ready:return "READY";case ProviderState::degraded:return "DEGRADED";case ProviderState::reconnecting:return "RECONNECTING";case ProviderState::error:return "ERROR";case ProviderState::stopping:return "STOPPING";}return "ERROR"; }
std::string_view to_string(DataQuality value) noexcept { switch(value){case DataQuality::realtime:return "REALTIME";case DataQuality::delayed:return "DELAYED";case DataQuality::frozen:return "FROZEN";case DataQuality::best_effort:return "BEST_EFFORT";case DataQuality::unknown:return "UNKNOWN";}return "UNKNOWN"; }
std::string_view to_string(MarketEventType value) noexcept { switch(value){case MarketEventType::quote_snapshot:return "quote_snapshot";case MarketEventType::trade_tick:return "trade_tick";case MarketEventType::bid_ask_tick:return "bid_ask_tick";case MarketEventType::depth_update:return "depth_update";case MarketEventType::bar:return "bar";}return "unknown"; }
std::optional<ProviderId> provider_id_from_string(std::string_view value) noexcept { if(value=="synthetic")return ProviderId::synthetic;if(value=="ctp")return ProviderId::ctp;if(value=="ibkr")return ProviderId::ibkr;if(value=="akshare")return ProviderId::akshare;return std::nullopt; }
std::optional<DataQuality> data_quality_from_string(std::string_view value) noexcept {if(value=="REALTIME")return DataQuality::realtime;if(value=="DELAYED")return DataQuality::delayed;if(value=="FROZEN")return DataQuality::frozen;if(value=="BEST_EFFORT")return DataQuality::best_effort;if(value=="UNKNOWN")return DataQuality::unknown;return std::nullopt;}
std::optional<MarketEventType> market_event_type_from_string(std::string_view value) noexcept {if(value=="quote_snapshot")return MarketEventType::quote_snapshot;if(value=="trade_tick")return MarketEventType::trade_tick;if(value=="bid_ask_tick")return MarketEventType::bid_ask_tick;if(value=="depth_update")return MarketEventType::depth_update;if(value=="bar")return MarketEventType::bar;return std::nullopt;}
}
