set(CTP_SDK_ROOT "" CACHE PATH "Root of the operator-supplied CTP market-data SDK")
if(NOT CTP_SDK_ROOT)
  message(FATAL_ERROR "ENABLE_CTP=ON requires -DCTP_SDK_ROOT=/path/to/operator-supplied/sdk")
endif()
find_path(CTP_INCLUDE_DIR ThostFtdcMdApi.h HINTS "${CTP_SDK_ROOT}" PATH_SUFFIXES include)
if(NOT CTP_INCLUDE_DIR)
  file(GLOB_RECURSE CTP_HEADER_CANDIDATES LIST_DIRECTORIES false "${CTP_SDK_ROOT}/*/ThostFtdcMdApi.h")
  list(LENGTH CTP_HEADER_CANDIDATES CTP_HEADER_COUNT)
  if(CTP_HEADER_COUNT EQUAL 1)
    list(GET CTP_HEADER_CANDIDATES 0 CTP_HEADER)
    get_filename_component(CTP_INCLUDE_DIR "${CTP_HEADER}" DIRECTORY)
  elseif(CTP_HEADER_COUNT GREATER 1)
    message(FATAL_ERROR "CTP_SDK_ROOT contains multiple SDK headers; point it at one version directory")
  endif()
endif()
find_library(CTP_MD_LIBRARY NAMES thostmduserapi_se thostmduserapi HINTS "${CTP_SDK_ROOT}" "${CTP_INCLUDE_DIR}" PATH_SUFFIXES lib lib64)
if(NOT CTP_MD_LIBRARY)
  find_file(CTP_MD_LIBRARY NAMES thostmduserapi_se.so thostmduserapi.so HINTS "${CTP_SDK_ROOT}" "${CTP_INCLUDE_DIR}" PATH_SUFFIXES lib lib64)
endif()
include(FindPackageHandleStandardArgs)
find_package_handle_standard_args(CTP REQUIRED_VARS CTP_INCLUDE_DIR CTP_MD_LIBRARY)
if(CTP_FOUND AND NOT TARGET CTP::MdApi)
  set(CTP_STAGED_LIBRARY "${CMAKE_BINARY_DIR}/libthostmduserapi_se.so")
  configure_file("${CTP_MD_LIBRARY}" "${CTP_STAGED_LIBRARY}" COPYONLY)
  add_library(CTP::MdApi UNKNOWN IMPORTED)
  set_target_properties(CTP::MdApi PROPERTIES
    IMPORTED_LOCATION "${CTP_STAGED_LIBRARY}"
    IMPORTED_NO_SONAME TRUE
    INTERFACE_INCLUDE_DIRECTORIES "${CTP_INCLUDE_DIR}")
endif()
