set(CTP_SDK_ROOT "" CACHE PATH "Root of the operator-supplied CTP market-data SDK")
find_path(CTP_INCLUDE_DIR ThostFtdcMdApi.h HINTS "${CTP_SDK_ROOT}" PATH_SUFFIXES include)
find_library(CTP_MD_LIBRARY NAMES thostmduserapi_se thostmduserapi HINTS "${CTP_SDK_ROOT}" PATH_SUFFIXES lib lib64)
include(FindPackageHandleStandardArgs)
find_package_handle_standard_args(CTP REQUIRED_VARS CTP_INCLUDE_DIR CTP_MD_LIBRARY)
if(CTP_FOUND AND NOT TARGET CTP::MdApi)
  add_library(CTP::MdApi UNKNOWN IMPORTED)
  set_target_properties(CTP::MdApi PROPERTIES IMPORTED_LOCATION "${CTP_MD_LIBRARY}" INTERFACE_INCLUDE_DIRECTORIES "${CTP_INCLUDE_DIR}")
endif()
